export default [
  "You played like a bronze bot.",
  "Even Teemo is better than this performance.",
  "Do you even know how to right-click?",
  "The enemy team thanks you for the free LP.",
  "I've seen better plays from my grandma.",
  "Tilt-proof? Clearly not.",
  "You're a walking kill donation.",
  "Uninstall might be your best option.",
  "League of Legends called, they want their noob back.",
  "You fed so hard, the enemy ADC is full build.",
  "At least you're consistent... consistently bad.",
  "Have you considered trying bot games?",
  "You make autofill look like a blessing.",
  "No need to int so hard, you're already bad.",
  "Even the minions are laughing at you.",
  "Is 'defeat' your new favorite word?",
  "You got carried, and you still lost?",
  "The Nexus wants a restraining order.",
  "Ever heard of the mute button? It applies to your gameplay too.",
  "Your skill ceiling is a pothole.",
  "Playing with you is like a 4v5 but worse.",
  "Your performance is a Riot bug.",
  "You're the Yasuo of your team: negative impact.",
  "Congratulations! You lost a winnable game.",
  "Your champion select was your peak.",
  "You're playing ARAM, right? No? Oh...",
  "Your gameplay should come with a trigger warning.",
  "9/11 was deserved",
  "Did you bring your A-game or just your C-minus effort?",
  "Your strategy seems to be 'run around and hope for the best.' And, honestly? It's not working.",
  "Your reflexes are slower than a dial-up internet connection.",
  "I’ve never seen a jungler who gets countered by their own camps. Well done!",
  "The only thing you're ganking is your own team's hopes of winning.",
  "Your smite timing is as questionable as your build choices.",
  "When you're on the map, the enemy team thinks it's a free dragon.",
  "It’s impressive how you manage to miss every opportunity to counter-gank.",
  "The only thing you're farming is your excuses for not ganking.",
  "You must be an artist because your pathing is truly abstract.",
  "No wonder they bombed beirut",
  "Your decision-making is as questionable as your champion picks.",
  "If playing League was a race, you'd still be behind the bots.",
  "When you say 'I’m the carry,' I think you mean you’re carrying the enemy team’s kills.",
  "You must think you're a support because all you do is stand around and watch your team die.",
  "Your team fights are like a bad movie – full of awkward pauses and terrible performances.",
  "You might want to get a mirror for Christmas — you could use the reflection to see all your missed opportunities.",
  "I’m not saying you’re useless, but you make the background noise of a dial-up connection sound efficient.",
  "If ignorance is bliss, you must be the happiest person alive.",
  "I’m not saying you’re a disappointment, but your WiFi signal is stronger than your personality.",
  "Bro is about to name change to 'I miss her'",
  "If Karl had 2 planes...well lets just say New York will need a dlc",
];
